name: Hoang Stark's Blog
description: think simple. be unique.
meta_description: "Hoang Stark's Blog about Technology, Programing, Smartphones and Web Design."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: http://iam.hoangstark.com/
domain_name: 'http://iam.hoangstark.com'

# Details for the RSS feed generator
url:            'http://iam.hoangstark.com'
author:         'Hoang Stark'

gems:
  - jekyll-feed
